# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: CMake on Windows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  c_ProjectName: "PropertyEditor"

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
      with:  # 必须用 with 包裹参数
        submodules: recursive  # 关键：递归克隆子模块, 操作包含 git submodule update --init --remote
        token: ${{ secrets.GITHUB_TOKEN }}  # 使用 GitHub 自动生成的 Token, 用于更新 submodule

    - name: Check Submodules
      shell: cmd
      run: |
        echo 检查是否更新 Submodules
        dir ThirdParty\CMakeProjectFramework
        
    - name: Install VS2015 Build Tools
      shell: powershell
      run: |
        choco install visualstudio2015buildtools -y --no-progress
        # 添加环境变量
        $v140Path = "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat"
        if (-not (Test-Path $v140Path)) {
          throw "VS2015 tools installation failed!"
        }

    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      #run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
      shell: cmd  # 显式指定使用 CMD 解释器
      working-directory: Build/${{env.c_ProjectName}}/Windows
      run: |
        echo 当前工作目录: %cd%
        Generate.bat

    - name: Build
      # Build your program with the given configuration
      #run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      shell: cmd  # 显式指定使用 CMD 解释器
      working-directory: Build/${{env.c_ProjectName}}/Windows
      run: |
        Build.bat

    # - name: Run
    #   shell: cmd
    #   working-directory: Build/${{env.c_ProjectName}}/Windows/DefaultBuild/Release/bin
    #   run: |
    #     ${{env.c_ProjectName}}.exe


    #- name: Test
    #  working-directory: ${{github.workspace}}/build
    #  # Execute tests defined by the CMake configuration.
    #  # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
    #  run: ctest -C ${{env.BUILD_TYPE}}

